# Generated by Django 5.0.6 on 2024-07-01 14:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desciption', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateField(default=datetime.date(2024, 7, 1))),
                ('taskCreator', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='User.user')),
            ],
        ),
    ]
